#!/usr/bin/python3

# Converts the raw data format generated by Gimp
# to a packed format where each byte represents two pixels 
# from a color indexed image with 16 colors (4 bits per pixel)

# The whole process goes like this
# 1. Edit the svg original version
# 2. Select the complete drawing, export to png. Must be 800x280
# 3. Open in Gimp
# 4. Convert to indexed color, 16 colors (4bpp)
# 5. Export to raw data, default options
# 6. Use this script to process the raw data file (.data extension)
# 7. Use the palette file to create the hardcoded palette in panel.sv


import getopt, sys

infile = sys.argv[1]
outfile = sys.argv[2]


with open(infile, "rb") as fi:
	with open(outfile, "wb") as fo:
		while idata := fi.read(4):
			val = ((idata[0] & 0x0f) << 4) | (idata[2] & 0x0f)
			fo.write(val.to_bytes(1,'big'))

